### PR TITLE
Fix submodules in `trace`.

### PR DESCRIPTION
**Pull request by samth**

### CODE REVIEW

**Comment by samth** [comment]
@mflatt or @rfindler I'm not sure who the right person to review this is.

**Comment by mflatt** [comment]
@samth It's possible that I knew this code at some point, but it's not familiar to me now

**Comment by samth** [comment]
The last person who made a meaningful commit here was @rfindler, but that was a long time ago.

**Comment by rfindler** [comment]
I just flipped thru the code and don't recognize it at all. I don't think
I'm better positioned than anyone else, I'm sorry to say.

**Comment by samth** [comment]
Looks like this code was originally by @jbclements and was last meaningfully changed in 2004. I'm just going to merge this fix in the absence of someone who knows this code.

**Comment by rfindler** [comment]
I think that if you have test cases whose output changes as a result of
this change, that is exactly the right thing and if you don't then someone
should make them.

Since I'm complaining :), if you can't do that after giving it a "college
try" (cough cough), I will do my best to do it.

Is that fair?

Robby

**Comment by samth** [comment]
I added a file which will break in DrDr if this code starts failing, and which would have broken prior to my change. Look good?

**Comment by rfindler** [comment]
Yes, perfect! I see it fails with my version. Thanks!

**Pull request merged**
